version: '2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'always'

    ports:
      - 80:3000
    labels:
      - convox.start.shift=2
      - convox.balancer=true
      - convox.health.timeout=30
      - convox.port.443.protocol=https